var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/transfers/new/page.js")
R.c("server/chunks/ssr/_0d5b3ff0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d5aaa26._.js")
R.c("server/chunks/ssr/_f3108623._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5bc9d735._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ecbddb6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__3f72e610._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_transfers_new_page_actions_de81d03b.js")
R.m(55523)
module.exports=R.m(55523).exports
