var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/sales/page.js")
R.c("server/chunks/ssr/_bcf3b736._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d5aaa26._.js")
R.c("server/chunks/ssr/_3eb2db5a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5bc9d735._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ecbddb6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__3f72e610._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_sales_page_actions_387cd0a2.js")
R.m(12702)
module.exports=R.m(12702).exports
